### ISSUE TITLE
Support code view highlight in Recorder

### ISSUE THREAD

**Issue by jecfish** [WebPageTest/recorder-to-webpagetest-chrome-extension#11]
Chrome 110 launches a new "Show code and highlight" feature.

**How to test**
You can test this feature with the latest Chrome Canary

1. Open a recording in the Recorder, click "Show code".
2. Hover over each step, the code should highlight accordingly.

**Action required**
1. Your extension needs to update to the latest [Puppeteer Replay](https://github.com/puppeteer/replay). 
2. Rebuild & publish a new version to Web Store
3. That's all! 

If your extension doesn't have Puppeteer Replay as dependency, you can implement the [sourcemaps] (https://github.com/puppeteer/replay/blob/main/src/stringify.ts#L68) yourself to make it work.

*my gif has pretty low res.*
![ezgif-4-33a0309279](https://user-images.githubusercontent.com/5917927/213026696-fe12fe0b-1229-49e0-9555-5221160b8f6c.gif)

**Comment by jecfish** [comment]
@Siddhantshukla814 fyi!

**Comment by Siddhantshukla814** [comment]
Hi @jecfish could you share an example of sourcemaps implementation?

**Comment by OrKoN** [comment]
@Siddhantshukla814 you can see the implementation starting here https://github.com/puppeteer/replay/blob/main/src/stringify.ts#L68

**Comment by Siddhantshukla814** [comment]
Hi @OrKoN, currently this extension don't use puppeteer/replay library for generating the custom script
I was wondering is there any doc that could help me with the step-by-step process to consume puppeteer/replay to generate custom scripts?

**Comment by OrKoN** [comment]
@Siddhantshukla814 we don't have a dedicated step-by-step guide but we have [API docs](https://github.com/puppeteer/replay/tree/main/docs/api) and some real-world examples like [Cypress](https://github.com/cypress-io/cypress-chrome-recorder/blob/main/src/CypressStringifyExtension.ts) as well as [smaller sample code](https://github.com/puppeteer/replay/blob/main/examples/extend-runner/main.js).

cc @jecfish

**Comment by Siddhantshukla814** [comment]
Thank you!
Forgot to close this issue as this has been resolved here https://github.com/WebPageTest/Recorder-To-WPT-Script/pull/14

https://www.npmjs.com/package/webpagetest-chrome-recorder
